### ISSUE TITLE
Repo name typo

### ISSUE THREAD

**Issue by redraw** [patriciogonzalezvivo/.glslScreensaver#1]
hey! great idea. just installed it. 
there's a typo that prevents from running, you might just change the path (`.glslScreenSaver` to `.glslScreensaver`) to match your repo name, or just change your repo name to `.glslScreenSaver`
https://github.com/patriciogonzalezvivo/.glslScreensaver/blob/0747c43e805a2bc763928d83bcfd96bd5a779cef/run.sh#L4
https://github.com/patriciogonzalezvivo/.glslScreensaver/blob/0747c43e805a2bc763928d83bcfd96bd5a779cef/init.sh#L12

**Comment by patriciogonzalezvivo** [comment]
oh! thanks for that I will change the repo name
